spring.application.name=springboot

##===============
## DB : local
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:jdbc:postgresql://losthost:5432/studydb
#spring.datasource.username=root
#spring.datasource.password=alsdn2283

## windows upload a path
#study.springboot.upload-path=C:/JMW/src/full_study/upload


##===============

##===============
# DB : ubuntu docker
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://192.168.219.191:5432/studydb
spring.datasource.username=jmw
spring.datasource.password=0220

# Mac upload path
study.springboot.upload-path=/Users/minwoo/workspace/study/full_study/upload

##===============

# jpa
spring.jpa.database=PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false

# SQL \uB85C\uAE45
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.properties.hibernate.format_sql=true

# jwt secret key
study.springboot.secret-key=mySecretKeyForJWTTokenGenerationThatIsLongEnoughForHS512AlgorithmWithAtLeast64Characters

# file upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB





