# 코드그룹
CREATE TABLE CODE_GROUP
(
    GROUP_CODE VARCHAR(3) NOT NULL,
    GROUP_NAME VARCHAR(30) NOT NULL ,
    REG_DATE DATETIME,
    UPD_DATE DATETIME,
    USE_YN VARCHAR(1),
    PRIMARY KEY (GROUP_CODE)
);

ALTER TABLE CODE_GROUP COMMENT '공통코드 그룹 테이블';
ALTER TABLE CODE_GROUP MODIFY COLUMN GROUP_CODE VARCHAR(3) NOT NULL COMMENT '그룹코드';
ALTER TABLE CODE_GROUP MODIFY COLUMN GROUP_NAME VARCHAR(30) NOT NULL COMMENT '그룹명';
ALTER TABLE CODE_GROUP MODIFY COLUMN REG_DATE DATETIME COMMENT '등록일시';
ALTER TABLE CODE_GROUP MODIFY COLUMN UPD_DATE DATETIME COMMENT '수정일시';
ALTER TABLE CODE_GROUP MODIFY COLUMN USE_YN VARCHAR(1) COMMENT '사용여부';

# 코드상세
CREATE TABLE CODE_DETAIL
(

    GROUP_CODE VARCHAR(3) NOT NULL ,
    CODE_VALUE VARCHAR(3) NOT NULL ,
    CODE_NAME VARCHAR(30) NOT NULL ,
    SORT_SEQ INTEGER NOT NULL ,
    REG_DATE DATETIME,
    UPD_DATE DATETIME,
    USE_YN VARCHAR(1),
    PRIMARY KEY (GROUP_CODE, CODE_VALUE)
);

ALTER TABLE CODE_DETAIL COMMENT '공통코드 상세 테이블';
ALTER TABLE CODE_DETAIL MODIFY COLUMN GROUP_CODE VARCHAR(3) NOT NULL COMMENT '그룹코드';
ALTER TABLE CODE_DETAIL MODIFY COLUMN CODE_VALUE VARCHAR(3) NOT NULL COMMENT '코드값';
ALTER TABLE CODE_DETAIL MODIFY COLUMN CODE_NAME VARCHAR(30) NOT NULL COMMENT '코드명';
ALTER TABLE CODE_DETAIL MODIFY COLUMN SORT_SEQ INTEGER NOT NULL COMMENT '정렬순서';
ALTER TABLE CODE_DETAIL MODIFY COLUMN REG_DATE DATETIME COMMENT '등록일시';
ALTER TABLE CODE_DETAIL MODIFY COLUMN UPD_DATE DATETIME COMMENT '수정일시';
ALTER TABLE CODE_DETAIL MODIFY COLUMN USE_YN VARCHAR(1) COMMENT '사용여부';


ALTER TABLE CODE_DETAIL
    ADD CONSTRAINT FK_CODE_DETAIL_GROUP_CODE
        FOREIGN KEY (GROUP_CODE) REFERENCES CODE_GROUP(GROUP_CODE);

# 회원
CREATE TABLE MEMBER
(
    USER_NO BIGINT NOT NULL AUTO_INCREMENT,
    USER_ID VARCHAR(50) NOT NULL ,
    USER_PW VARCHAR(200) NOT NULL ,
    USER_NAME VARCHAR(100) NOT NULL ,
    JOB VARCHAR(3) NOT NULL ,
    COIN INTEGER NOT NULL ,
    REG_DATE DATETIME,
    UPD_DATE DATETIME,
    PRIMARY KEY (USER_NO)
);

ALTER TABLE MEMBER COMMENT '회원 정보 테이블';
ALTER TABLE MEMBER MODIFY COLUMN USER_NO BIGINT NOT NULL AUTO_INCREMENT COMMENT '사용자번호';
ALTER TABLE MEMBER MODIFY COLUMN USER_ID VARCHAR(50) NOT NULL COMMENT '사용자 ID';
ALTER TABLE MEMBER MODIFY COLUMN USER_PW VARCHAR(200) NOT NULL COMMENT '사용자 비밀번호';
ALTER TABLE MEMBER MODIFY COLUMN USER_NAME VARCHAR(100) NOT NULL COMMENT '사용자명';
ALTER TABLE MEMBER MODIFY COLUMN JOB VARCHAR(3) NOT NULL COMMENT '직업';
ALTER TABLE MEMBER MODIFY COLUMN COIN INTEGER NOT NULL COMMENT '코인';
ALTER TABLE MEMBER MODIFY COLUMN REG_DATE DATETIME COMMENT '등록일시';
ALTER TABLE MEMBER MODIFY COLUMN UPD_DATE DATETIME COMMENT '수정일시';

# 회원권한
CREATE TABLE MEMBER_AUTH
(
    USER_AUTH_NO BIGINT NOT NULL AUTO_INCREMENT,
    USER_NO BIGINT,
    AUTH VARCHAR(50),
    REG_DATE DATETIME,
    UPD_DATE DATETIME,
    PRIMARY KEY (USER_AUTH_NO)
);

ALTER TABLE MEMBER_AUTH COMMENT '회원 권한 테이블';
ALTER TABLE MEMBER_AUTH MODIFY COLUMN USER_AUTH_NO BIGINT NOT NULL AUTO_INCREMENT COMMENT '사용자권한번호';
ALTER TABLE MEMBER_AUTH MODIFY COLUMN USER_NO BIGINT COMMENT '사용자번호';
ALTER TABLE MEMBER_AUTH MODIFY COLUMN AUTH VARCHAR(50) COMMENT '권한';
ALTER TABLE MEMBER_AUTH MODIFY COLUMN REG_DATE DATETIME COMMENT '등록일시';
ALTER TABLE MEMBER_AUTH MODIFY COLUMN UPD_DATE DATETIME COMMENT '수정일시';

ALTER TABLE MEMBER_AUTH
    ADD CONSTRAINT FK_MEMBER_AUTH_USER_NO
        FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO);

# 게시판
CREATE TABLE BOARD
(
    BOARD_NO BIGINT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(200) NOT NULL ,
    WRITER VARCHAR(50) NOT NULL ,
    CONTENT LONGTEXT,
    REG_DATE DATETIME,
    UPD_DATE DATETIME,
    PRIMARY KEY (BOARD_NO)
);

ALTER TABLE BOARD COMMENT '게시판 테이블';
ALTER TABLE BOARD MODIFY COLUMN BOARD_NO BIGINT NOT NULL AUTO_INCREMENT COMMENT '게시글번호';
ALTER TABLE BOARD MODIFY COLUMN TITLE VARCHAR(200) NOT NULL COMMENT '제목';
ALTER TABLE BOARD MODIFY COLUMN WRITER VARCHAR(50) NOT NULL COMMENT '작성자';
ALTER TABLE BOARD MODIFY COLUMN CONTENT LONGTEXT COMMENT '내용';
ALTER TABLE BOARD MODIFY COLUMN REG_DATE DATETIME COMMENT '등록일시';
ALTER TABLE BOARD MODIFY COLUMN UPD_DATE DATETIME COMMENT '수정일시';

# 공지사항
CREATE TABLE NOTICE
(
    NOTICE_NO BIGINT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(200) NOT NULL ,
    CONTENT LONGTEXT,
    REG_DATE DATETIME,
    UPD_DATE DATETIME,
    PRIMARY KEY (NOTICE_NO)
);

ALTER TABLE NOTICE COMMENT '공지사항 테이블';
ALTER TABLE NOTICE MODIFY COLUMN NOTICE_NO BIGINT NOT NULL AUTO_INCREMENT COMMENT '공지번호';
ALTER TABLE NOTICE MODIFY COLUMN TITLE VARCHAR(200) NOT NULL COMMENT '제목';
ALTER TABLE NOTICE MODIFY COLUMN CONTENT LONGTEXT COMMENT '내용';
ALTER TABLE NOTICE MODIFY COLUMN REG_DATE DATETIME COMMENT '등록일시';
ALTER TABLE NOTICE MODIFY COLUMN UPD_DATE DATETIME COMMENT '수정일시';

# 상품
CREATE TABLE ITEM
(
    ITEM_ID BIGINT NOT NULL AUTO_INCREMENT,
    ITEM_NAME VARCHAR(50) NOT NULL ,
    PRICE INTEGER,
    DESCRIPTION VARCHAR(250),
    PICTURE_URL VARCHAR(200),
    PREVIEW_URL VARCHAR(200),
    REG_DATE DATETIME,
    UPD_DATE DATETIME,
    PRIMARY KEY (ITEM_ID)
);

ALTER TABLE ITEM COMMENT '상품 정보 테이블';
ALTER TABLE ITEM MODIFY COLUMN ITEM_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '상품ID';
ALTER TABLE ITEM MODIFY COLUMN ITEM_NAME VARCHAR(50) NOT NULL COMMENT '상품명';
ALTER TABLE ITEM MODIFY COLUMN PRICE INTEGER COMMENT '가격 (코인)';
ALTER TABLE ITEM MODIFY COLUMN DESCRIPTION VARCHAR(250) COMMENT '상품설명';
ALTER TABLE ITEM MODIFY COLUMN PICTURE_URL VARCHAR(200) COMMENT '이미지 URL';
ALTER TABLE ITEM MODIFY COLUMN PREVIEW_URL VARCHAR(200) COMMENT '미리보기 URL';
ALTER TABLE ITEM MODIFY COLUMN REG_DATE DATETIME COMMENT '등록일시';
ALTER TABLE ITEM MODIFY COLUMN UPD_DATE DATETIME COMMENT '수정일시';

# 사용자 상품
CREATE TABLE USER_ITEM
(
    USER_ITEM_NO BIGINT NOT NULL AUTO_INCREMENT,
    USER_NO BIGINT,
    ITEM_ID BIGINT,
    REG_DATE DATETIME,
    UPD_DATE DATETIME,
    PRIMARY KEY (USER_ITEM_NO)
);

ALTER TABLE USER_ITEM COMMENT '사용자 상품 테이블';
ALTER TABLE USER_ITEM MODIFY COLUMN USER_ITEM_NO BIGINT NOT NULL AUTO_INCREMENT COMMENT '사용자상품번호';
ALTER TABLE USER_ITEM MODIFY COLUMN USER_NO BIGINT COMMENT '사용자번호';
ALTER TABLE USER_ITEM MODIFY COLUMN ITEM_ID BIGINT COMMENT '상품ID';
ALTER TABLE USER_ITEM MODIFY COLUMN REG_DATE DATETIME COMMENT '구매일시';
ALTER TABLE USER_ITEM MODIFY COLUMN UPD_DATE DATETIME COMMENT '수정일시';

# 자료실
CREATE TABLE PDS
(
    ITEM_ID BIGINT NOT NULL AUTO_INCREMENT,
    ITEM_NAME VARCHAR(255),
    VIEW_CNT INTEGER,
    DESCRIPTION VARCHAR(255),
    REG_DATE DATETIME,
    UPD_DATE DATETIME,
    PRIMARY KEY (ITEM_ID)
);

ALTER TABLE PDS COMMENT '자료실 테이블';
ALTER TABLE PDS MODIFY COLUMN ITEM_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '자료ID';
ALTER TABLE PDS MODIFY COLUMN ITEM_NAME VARCHAR(255) COMMENT '자료명';
ALTER TABLE PDS MODIFY COLUMN VIEW_CNT INTEGER COMMENT '조회수';
ALTER TABLE PDS MODIFY COLUMN DESCRIPTION VARCHAR(255) COMMENT '자료설명';
ALTER TABLE PDS MODIFY COLUMN REG_DATE DATETIME COMMENT '등록일시';
ALTER TABLE PDS MODIFY COLUMN UPD_DATE DATETIME COMMENT '수정일시';

# 자료실 첨부 파일
CREATE TABLE PDS_FILE
(
    PDS_FILE_ID BIGINT NOT NULL AUTO_INCREMENT,
    ITEM_ID BIGINT,
    FULL_NAME VARCHAR(200),
    DOWN_CNT INTEGER,
    REG_DATE DATETIME,
    UPD_DATE DATETIME,
    PRIMARY KEY (PDS_FILE_ID)
);

ALTER TABLE PDS_FILE COMMENT '자료실 첨부파일 테이블';
ALTER TABLE PDS_FILE MODIFY COLUMN PDS_FILE_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '파일ID';
ALTER TABLE PDS_FILE MODIFY COLUMN ITEM_ID BIGINT COMMENT '자료ID';
ALTER TABLE PDS_FILE MODIFY COLUMN FULL_NAME VARCHAR(200) COMMENT '파일 전체명';
ALTER TABLE PDS_FILE MODIFY COLUMN DOWN_CNT INTEGER COMMENT '다운로드 횟수';
ALTER TABLE PDS_FILE MODIFY COLUMN REG_DATE DATETIME COMMENT '등록일시';
ALTER TABLE PDS_FILE MODIFY COLUMN UPD_DATE DATETIME COMMENT '수정일시';

ALTER TABLE PDS_FILE
    ADD CONSTRAINT FK_PDS_FILE_ITEM_ID
        FOREIGN KEY (ITEM_ID) REFERENCES PDS (ITEM_ID);

# 충전 내역
CREATE TABLE CHARGE_COIN_HISTORY
(
    HISTORY_NO BIGINT NOT NULL AUTO_INCREMENT,
    USER_NO BIGINT,
    AMOUNT INTEGER NOT NULL ,
    REG_DATE DATETIME,
    UPD_DATE DATETIME,
    PRIMARY KEY (HISTORY_NO)
);

ALTER TABLE CHARGE_COIN_HISTORY COMMENT '코인 충전 내역 테이블';
ALTER TABLE CHARGE_COIN_HISTORY MODIFY COLUMN HISTORY_NO BIGINT NOT NULL AUTO_INCREMENT COMMENT '이력번호';
ALTER TABLE CHARGE_COIN_HISTORY MODIFY COLUMN USER_NO BIGINT COMMENT '사용자번호';
ALTER TABLE CHARGE_COIN_HISTORY MODIFY COLUMN AMOUNT INTEGER NOT NULL COMMENT '충전금액';
ALTER TABLE CHARGE_COIN_HISTORY MODIFY COLUMN REG_DATE DATETIME COMMENT '충전일시';
ALTER TABLE CHARGE_COIN_HISTORY MODIFY COLUMN UPD_DATE DATETIME COMMENT '수정일시';

# 지급 내역
CREATE TABLE PAY_COIN_HISTORY
(
    HISTORY_NO BIGINT NOT NULL AUTO_INCREMENT,
    USER_NO BIGINT,
    ITEM_ID BIGINT,
    ITEM_NAME VARCHAR(255),
    AMOUNT INTEGER NOT NULL ,
    REG_DATE DATETIME,
    UPD_DATE DATETIME,
    PRIMARY KEY (HISTORY_NO)
);

ALTER TABLE PAY_COIN_HISTORY COMMENT '코인 지급 내역 테이블';
ALTER TABLE PAY_COIN_HISTORY MODIFY COLUMN HISTORY_NO BIGINT NOT NULL AUTO_INCREMENT COMMENT '이력번호';
ALTER TABLE PAY_COIN_HISTORY MODIFY COLUMN USER_NO BIGINT COMMENT '사용자번호';
ALTER TABLE PAY_COIN_HISTORY MODIFY COLUMN ITEM_ID BIGINT COMMENT '상품ID';
ALTER TABLE PAY_COIN_HISTORY MODIFY COLUMN ITEM_NAME VARCHAR(255) COMMENT '상품명';
ALTER TABLE PAY_COIN_HISTORY MODIFY COLUMN AMOUNT INTEGER NOT NULL COMMENT '사용금액';
ALTER TABLE PAY_COIN_HISTORY MODIFY COLUMN REG_DATE DATETIME COMMENT '사용일시';
ALTER TABLE PAY_COIN_HISTORY MODIFY COLUMN UPD_DATE DATETIME COMMENT '수정일시';

# 접근 로그
CREATE TABLE ACCESS_LOG
(
    LOG_NO BIGINT NOT NULL AUTO_INCREMENT,
    REQUEST_URL VARCHAR(200) NOT NULL ,
    CLASS_NAME VARCHAR(100) NOT NULL ,
    CLASS_SIMPLE_NAME VARCHAR(50) NOT NULL ,
    METHOD_NAME VARCHAR(100) NOT NULL ,
    REMOTE_ADDR VARCHAR(50) NOT NULL ,
    REG_DATE DATETIME,
    UPD_DATE DATETIME,
    PRIMARY KEY (LOG_NO)
);

ALTER TABLE ACCESS_LOG COMMENT '시스템 접근 로그 테이블';
ALTER TABLE ACCESS_LOG MODIFY COLUMN LOG_NO BIGINT NOT NULL AUTO_INCREMENT COMMENT '로그번호';
ALTER TABLE ACCESS_LOG MODIFY COLUMN REQUEST_URL VARCHAR(200) NOT NULL COMMENT '요청 URL';
ALTER TABLE ACCESS_LOG MODIFY COLUMN CLASS_NAME VARCHAR(100) NOT NULL COMMENT '컨트롤러 클래스명';
ALTER TABLE ACCESS_LOG MODIFY COLUMN CLASS_SIMPLE_NAME VARCHAR(50) NOT NULL COMMENT '컨트롤러 클래스명 (요약)';
ALTER TABLE ACCESS_LOG MODIFY COLUMN METHOD_NAME VARCHAR(100) NOT NULL COMMENT '메서드명';
ALTER TABLE ACCESS_LOG MODIFY COLUMN REMOTE_ADDR VARCHAR(50) NOT NULL COMMENT '클라이언트 IP주소';
ALTER TABLE ACCESS_LOG MODIFY COLUMN REG_DATE DATETIME COMMENT '접근일시';
ALTER TABLE ACCESS_LOG MODIFY COLUMN UPD_DATE DATETIME COMMENT '수정일시';

# 서비스 성능 로그
CREATE TABLE PERFORMANCE_LOG
(
    LOG_NO BIGINT NOT NULL AUTO_INCREMENT,
    SIGNATURE_NAME VARCHAR(50) NOT NULL ,
    SIGNATURE_TYPE_NAME VARCHAR(100) NOT NULL ,
    DURATION_TIME BIGINT,
    REG_DATE DATETIME,
    UPD_DATE DATETIME,
    PRIMARY KEY (LOG_NO)
);

ALTER TABLE PERFORMANCE_LOG COMMENT '서비스 성능 로그 테이블';
ALTER TABLE PERFORMANCE_LOG MODIFY COLUMN LOG_NO BIGINT NOT NULL AUTO_INCREMENT COMMENT '로그번호';
ALTER TABLE PERFORMANCE_LOG MODIFY COLUMN SIGNATURE_NAME VARCHAR(50) NOT NULL COMMENT '시그니처명';
ALTER TABLE PERFORMANCE_LOG MODIFY COLUMN SIGNATURE_TYPE_NAME VARCHAR(100) NOT NULL COMMENT '시그니처 타입명';
ALTER TABLE PERFORMANCE_LOG MODIFY COLUMN DURATION_TIME BIGINT COMMENT '실행시간';
ALTER TABLE PERFORMANCE_LOG MODIFY COLUMN REG_DATE DATETIME COMMENT '실행일시';
ALTER TABLE PERFORMANCE_LOG MODIFY COLUMN UPD_DATE DATETIME COMMENT '수정일시';
